package fastpurgev3

// AkamaiEnvironment represents Akamai's target environment type.
type AkamaiEnvironment string

type AkamaiPurgeStrategy string
type AkamaiPurgeType string

const (
	Production AkamaiEnvironment = "production"
	Staging    AkamaiEnvironment = "staging"

	Invalidate AkamaiPurgeStrategy = "invalidate"
	Delete     AkamaiPurgeStrategy = "delete"

	URL      AkamaiPurgeType = "url"
	CPCode   AkamaiPurgeType = "cpcode"
	CacheTag AkamaiPurgeType = "tag"
)

type FastPurgeRequest struct {
	Hostname string   `json:"hostname,omitempty"`
	Objects  []string `json:"objects,omitempty"`
}

// Generated by https://quicktype.io

type FastPurgeResult struct {
	HTTPStatus       int64  `json:"httpStatus"`
	EstimatedSeconds int64  `json:"estimatedSeconds"`
	PurgeID          string `json:"purgeId"`
	SupportID        string `json:"supportId"`
	Detail           string `json:"detail"`
}
