name: Auto release

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  release:
    name: Create release
    runs-on: ['self-hosted']
    if: github.event.pull_request.merged == true
    steps:
      - name: Create release - minor
        id: create_release
        uses: zendesk/action-create-release@v1
        auto_increment_type: "minor"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

